### ISSUE TITLE
一部の曲が変換できない

### ISSUE THREAD

**Issue by Reiya0917milk** [nyoro-wrl/KoiotoOTCConverter#9]
一部の曲が変換できません。
<URLを削除しました>
<URLを削除しました>

**Comment by nyoro-wrl** [comment]
[Ver.1.3.3](https://github.com/nyoro-wrl/KoiotoOTCConverter/releases/tag/Ver.1.3.3)にて修正されました。

**Comment by nyoro-wrl** [comment]
@Reiya0917milk
修正投げるのはいいですが、アウトなURLは載せないでください。

**Comment by Reiya0917milk** [comment]
すみません 以後気をつけます
